DELETE FROM clan_members CASCADE;
DELETE FROM players CASCADE;
DELETE FROM clans CASCADE;
DELETE FROM migrations CASCADE;
DELETE FROM war_attacks CASCADE;
DELETE FROM war_members CASCADE;
DELETE FROM wars CASCADE;
DELETE FROM telegram_links CASCADE;