DROP TABLE IF EXISTS clan_members CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS clans CASCADE;
DROP TABLE IF EXISTS migrations CASCADE;
DROP TABLE IF EXISTS war_attacks CASCADE;
DROP TABLE IF EXISTS war_members CASCADE;
DROP TABLE IF EXISTS wars CASCADE;